-- This one was initially used to experiment with the API
-- CREATE TABLE guides (
--     guide_id INT AUTO_INCREMENT PRIMARY KEY,
--     author_id INT NOT NULL,
--     title VARCHAR(255) NOT NULL,
--     content TEXT NOT NULL,
--     date_published TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (author_id) REFERENCES users (user_id)
-- );
